service: medical-departures-app

provider:
 name: aws
 runtime: nodejs14.17.3
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-2

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /


